[build.environment]
  node_version = "20"
  NPM_FLAGS = "--include=dev"

[build]
  command = "npm run build"
  publish = "/frontend/public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
